In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, average_precision_score,precision_score,f1_score,recall_score

# create confusion matrix
y_true = np.array([-1]*70 + [0]*160 + [1]*30)
y_pred = np.array([-1]*40 + [0]*20 + [1]*20 + 
                  [-1]*30 + [0]*80 + [1]*30 + 
                  [-1]*5 + [0]*15 + [1]*20)
cm = confusion_matrix(y_true, y_pred)
conf_matrix = pd.DataFrame(cm, index=['Cat','Dog','Pig'], columns=['Cat','Dog','Pig'])

print(y_true.shape)
print(y_pred.shape)
print('------Weighted------')
print('Weighted precision', precision_score(y_true, y_pred, average='weighted'))
print('Weighted recall', recall_score(y_true, y_pred, average='weighted'))
print('Weighted f1-score', f1_score(y_true, y_pred, average='weighted'))
print('------Macro------')
print('Macro precision', precision_score(y_true, y_pred, average='macro'))
print('Macro recall', recall_score(y_true, y_pred, average='macro'))
print('Macro f1-score', f1_score(y_true, y_pred, average='macro'))
print('------Micro------')
print('Micro precision', precision_score(y_true, y_pred, average='micro'))
print('Micro recall', recall_score(y_true, y_pred, average='micro'))
print('Micro f1-score', f1_score(y_true, y_pred, average='micro'))

KeyboardInterrupt: 

In [ ]:
a = [1,2,3]
b = a + [4]
b = tuple(b)
b

(1, 2, 3, 4)

: 

In [ ]:
import torch

ckp_path = '/home/huangjialong/projects/BiomedCLIP-PUNCE/mil-methods/output-model/output-test/resnet1-meanmil-ngc-customsplit/fold_0_model_best_auc.pt'
torch.load(ckp_path)
ckp_dict = torch.load(ckp_path)

In [ ]:
import csv
wsis = []
file_name = './simclr/train_label.csv'
with open(file_name, 'r') as f:
    lines = f.readlines()
    for row in lines:
        row = row.strip().split(',')
        wsis.append(row[0])
print(wsis)        


['BJXFK-LA-591455', 'c00567195', 'BJXFK-XXBA-579873', 'BJXFK-XA-575822', 'c00564281', 'BJXK-XIMEA-FFK-P-599781', 'BJXFK-YX577236', 'F22', 'BJXFK-XA576163', 'BJFFK-SCLC574253', 'C00564517', 'BJFFK-XA574864', 'BJFFK-XA573779', 'BJFFK-XA574570', 'BJXK-XIMEA-FFK-P-592670', 'BJXFK-YX575769', 'BJFFK-XA575058', 'F2', 'C00570399', 'BJXK-XIMEA-FFK-P-601186', 'BJXK-XIMEA-FFK-P-599581', 'BJXFK-XA577091', 'BJXFK-XA575834', 'BJXFK-XA583281', 'c00568834', 'F25', 'BJXFK-YX-576622', 'BJXFK-XA576692', 'BJFFK-XA571457', 'BJXFK-XA577014', 'c00569478', 'BJXFK-YX583088', 'BJXFK-XA577016', 'BJFFK-XA571327', 'C00569905', 'c00568308', 'BJFFK-SCLC572374', 'BJFFK-XA571332', 'c00567186', 'c00568523', 'BJFFK-XA572378', 'BJFFK-XA575640', 'BJXFK-YX584459', 'BJFFK-XA575740', 'BJXK-XIMEA-FFK-P-601001', 'BJXFK-XA-581051', 'BJXK-XIMEA-FFK-P-593609', 'c00568309', 'BJFFK-XA571956', 'BJFFK-XA570908', 'BJXK-XIMEA-FFK-P-602284', 'C00562488', 'BJXFK-XA579315', 'BJXK-XIMEA-FFK-P-598709', 'BJFFK-XA573780', 'BJFFK-XA571951', 'F

In [ ]:
import os
wsi_root = '/home1/wsi/tct/'
sub_paths = [
            'NILM',
            'POS'
        ]
wsi_dirs = []
for sub_path in sub_paths:
    wsi_dirs.extend([os.path.join(wsi_root, sub_path, wsi_name) for wsi_name in os.listdir(os.path.join(wsi_root, sub_path))])
# data_roots = list(map(lambda x: os.path.join(wsi_root, x), sub_paths))
# data_roots
# wsi_dirs = [os.path.join(wsi_root, sub_dir) for sub_dir in os.listdir(data_roots) ]
wsi_dirs

['/home1/wsi/tct/NILM/xCR20018818-NILM',
 '/home1/wsi/tct/NILM/xCY20005897-NILM',
 '/home1/wsi/tct/NILM/xCY20006000-NILM',
 '/home1/wsi/tct/NILM/xCY20006569-NILM',
 '/home1/wsi/tct/NILM/CX20179985-NILM',
 '/home1/wsi/tct/NILM/CX20166624-NILM',
 '/home1/wsi/tct/NILM/CX20175637-NILM',
 '/home1/wsi/tct/NILM/xCR20018330-NILM',
 '/home1/wsi/tct/NILM/xCY20008034-NILM',
 '/home1/wsi/tct/NILM/xCY20006621-NILM',
 '/home1/wsi/tct/NILM/xCR20018882-NILM',
 '/home1/wsi/tct/NILM/xCY20005843-NILM',
 '/home1/wsi/tct/NILM/CX20179988-NILM',
 '/home1/wsi/tct/NILM/xCR20018485-NILM',
 '/home1/wsi/tct/NILM/xCR20018268-NILM',
 '/home1/wsi/tct/NILM/xCY20006943-NILM',
 '/home1/wsi/tct/NILM/CX20152317-NILM',
 '/home1/wsi/tct/NILM/xCY20007765-NILM',
 '/home1/wsi/tct/NILM/CX20171594-NILM',
 '/home1/wsi/tct/NILM/202000822',
 '/home1/wsi/tct/NILM/CX20176960-NILM',
 '/home1/wsi/tct/NILM/xCY20006719-NILM',
 '/home1/wsi/tct/NILM/xCY20006691-NILM',
 '/home1/wsi/tct/NILM/xCY20007597-NILM',
 '/home1/wsi/tct/NILM/CX201749

In [ ]:
from torchvision import transforms
import glob

train_transform = transforms.Compose([transforms.RandomResizedCrop(224),
                                          transforms.RandomHorizontalFlip(p=0.5),
                                          transforms.ToTensor()])
    

train_set = Whole_Slide_Patchs_Ngc(
            data_dir='/home1/wsi/ngc-2023-1333/',
            train_label_path='/home/huangjialong/projects/BiomedCLIP-PUNCE/datatools/ngc_labels/ngc_train_label.csv',
            transform=train_transform
        )


In [ ]:
import numpy as np
import torch
import torch.nn.functional as f
from sklearn.metrics import roc_curve, roc_auc_score

n_classes = 5
y_label = np.random.randint(0,n_classes, (10))
y_pred = np.random.rand(10, n_classes)
y_pred = torch.softmax(torch.tensor(y_pred), dim=1)
y_label_one_hot = np.eye(n_classes)[y_label]
print(y_label_one_hot, y_pred)
roc_auc = dict()

for i in range(n_classes):
    roc_auc[i] = roc_auc_score(y_label_one_hot[:, i], y_pred[:, i])
roc_auc = list(roc_auc.values())
roc_auc_macro = np.mean(roc_auc)
roc_auc_macro

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]] tensor([[0.2765, 0.1852, 0.2274, 0.1506, 0.1602],
        [0.2159, 0.1409, 0.1849, 0.2888, 0.1695],
        [0.1244, 0.1427, 0.2141, 0.2983, 0.2204],
        [0.1451, 0.2369, 0.2650, 0.2379, 0.1151],
        [0.1354, 0.1046, 0.2688, 0.2269, 0.2644],
        [0.2930, 0.1570, 0.2331, 0.1355, 0.1814],
        [0.2257, 0.3268, 0.1634, 0.1427, 0.1414],
        [0.2123, 0.1062, 0.2431, 0.2417, 0.1966],
        [0.2173, 0.2060, 0.2000, 0.2304, 0.1462],
        [0.1517, 0.2533, 0.1651, 0.2723, 0.1577]], dtype=torch.float64)


ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

In [ ]:
train_set[10][0].shape

torch.Size([2, 3, 224, 224])

In [ ]:
import os
root_dir = '/home1/wsi/ngc-2023-224/'
sub_dirs = [
    'Unannotated_KSJ/Unannotated-KSJ-TCTNGC-NILM',
    'Unannotated_KSJ/Unannotated-KSJ-TCTNGC-POS',
    'Unannotated_XIMEA/Unannotated-XIMEA-TCTNGC-NILM',
    'Unannotated_XIMEA/Unannotated-XIMEA-TCTNGC-POS'
]
sum_wsi = 0
for sub_dir in sub_dirs:
    sub_dir_path = os.path.join(root_dir, sub_dir)
    sum_wsi += len(os.listdir(sub_dir_path))
sum_wsi
sum_images = 0

def count_fun(sub_dir):
    sum_images = 0
    input_dir_tmp = os.path.join(root_dir, sub_dir)
    for root, dirs, files in os.walk(input_dir_tmp):
        for filename in files:
            if filename.endswith('.jpg') or filename.endswith('.png') or filename.endswith('.jpeg'):
                sum_images += 1
    return sum_images 
for sub_dir in sub_dirs:
    sum_images += count_fun(sub_dir)
print(sum_images)

565720


In [ ]:
from torch import tensor
from torchmetrics.classification import BinarySpecificity
target = tensor([0, 1, 0, 1, 0, 1])
preds = tensor([0, 0, 1, 1, 0, 1])
metric = BinarySpecificity()
metric(preds, target)


tensor(0.6667)

In [ ]:
import torch

path = '/home/huangjialong/projects/BiomedCLIP-PUNCE/simclr/output-model/new-simclr-puc/biomed_simclr_infonce_filterGC_224_4*256/biomed_simclr_infonce_filterGC_224_4*256_epoch10.pt'
tensor = torch.load(path)
tensor

{'adapter': OrderedDict([('hide_layer.weight',
               tensor([[ 0.0109, -0.0350,  0.0311,  ...,  0.0307,  0.0095,  0.0083],
                       [-0.0034,  0.0327,  0.0025,  ..., -0.0300,  0.0202,  0.0268],
                       [ 0.0229,  0.0451,  0.0338,  ...,  0.0130, -0.0130,  0.0236],
                       ...,
                       [-0.0213,  0.0386,  0.0194,  ..., -0.0484, -0.0293, -0.0139],
                       [ 0.0197,  0.0509,  0.0287,  ..., -0.0375,  0.0119,  0.0043],
                       [ 0.0115,  0.0238,  0.0194,  ...,  0.0040, -0.0067, -0.0480]],
                      device='cuda:0')),
              ('hide_layer.bias',
               tensor([-0.2269,  0.2048,  0.1236,  0.0651,  0.0013,  0.0025,  0.1936,  0.0200,
                        0.2058,  0.2394,  0.2005,  0.4795,  0.3440, -0.0141,  0.6812,  0.0355,
                        0.5717, -0.5975,  0.0265, -0.0436, -0.1840, -0.1434,  0.1415, -0.0168,
                       -0.2090,  0.0154,  0.0908,  0.0

In [ ]:
import open_clip

model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')
tokenizer = open_clip.get_tokenizer('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')

In [ ]:
from PIL import Image

model.cuda()
img_path = '/home1/wsi/gc-224/NILM/202000767/1_10.jpg'
input = preprocess_val(Image.open(img_path)).unsqueeze(0).to('cuda')
img_feature, _, scalar = model(input)
img_feature.shape

img_feature1 = model.encode_image(input)
img_feature1.shape

img_feature2 = model.visual.trunk(input)

img_feature2 /= img_feature


In [ ]:
import torch.nn.functional as F
import torch

def fix_seed(seed):
    torch.manual_seed(seed) # 为CPU设置随机种子
    torch.cuda.manual_seed(seed) # 为当前GPU设置随机种子
    torch.cuda.manual_seed_all(seed)  # if you are using multi-GPU，为所有GPU设置随机种子
    torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

fix_seed(2024)
# Example of target with class indices
input = torch.randn(5, 3, requires_grad=True)
target = torch.randint(3, (5,), dtype=torch.int64)
print(input, target)
loss = F.cross_entropy(input, target)
loss

tensor([[-0.0404,  1.7260, -0.8140],
        [ 1.3722,  0.5060, -0.4823],
        [-0.7853,  0.6681, -0.4439],
        [ 0.1888,  0.5986,  0.6458],
        [ 0.6306, -1.4668, -0.6798]], requires_grad=True) tensor([0, 2, 2, 2, 1])


tensor(1.8474, grad_fn=<NllLossBackward0>)

In [ ]:
import torch.nn.functional as F
import torch

input = torch.tensor([[0,  1, -0.8140],
        [ 1.3722,  0.5060, -0.4823],
        [-0.7853,  0.6681, -0.4439],
        [ 0.1888,  0.5986,  0.6458],
        [ 0.6306, -1.4668, -0.6798]], dtype=torch.float32)
target = torch.tensor([0, 2, 2, 2, 1])
target = F.one_hot(target, num_classes=3).type(torch.float32)
loss = F.cross_entropy(input, target)
loss


tensor(1.8474)

In [ ]:
n = -torch.inf
input = torch.tensor([[1., n, n],])
target1 = torch.tensor([0])
target2 = torch.tensor([[2., 0., 0.],])
loss1 = F.cross_entropy(input, target1)
loss2 = F.cross_entropy(input, target2)
print(loss1, loss2)

tensor(0.) tensor(nan)


In [ ]:
for k, v in model.visual.named_parameters():
    print(k)

trunk.cls_token
trunk.pos_embed
trunk.patch_embed.proj.weight
trunk.patch_embed.proj.bias
trunk.blocks.0.norm1.weight
trunk.blocks.0.norm1.bias
trunk.blocks.0.attn.qkv.weight
trunk.blocks.0.attn.qkv.bias
trunk.blocks.0.attn.proj.weight
trunk.blocks.0.attn.proj.bias
trunk.blocks.0.norm2.weight
trunk.blocks.0.norm2.bias
trunk.blocks.0.mlp.fc1.weight
trunk.blocks.0.mlp.fc1.bias
trunk.blocks.0.mlp.fc2.weight
trunk.blocks.0.mlp.fc2.bias
trunk.blocks.1.norm1.weight
trunk.blocks.1.norm1.bias
trunk.blocks.1.attn.qkv.weight
trunk.blocks.1.attn.qkv.bias
trunk.blocks.1.attn.proj.weight
trunk.blocks.1.attn.proj.bias
trunk.blocks.1.norm2.weight
trunk.blocks.1.norm2.bias
trunk.blocks.1.mlp.fc1.weight
trunk.blocks.1.mlp.fc1.bias
trunk.blocks.1.mlp.fc2.weight
trunk.blocks.1.mlp.fc2.bias
trunk.blocks.2.norm1.weight
trunk.blocks.2.norm1.bias
trunk.blocks.2.attn.qkv.weight
trunk.blocks.2.attn.qkv.bias
trunk.blocks.2.attn.proj.weight
trunk.blocks.2.attn.proj.bias
trunk.blocks.2.norm2.weight
trunk.blocks.2

In [ ]:
import torch.nn as nn
import torch
import torch.nn.functional as F

class LinearAdapter(nn.Module):
    def __init__(self, input_dim):
        super(LinearAdapter, self).__init__()
        self.hide_layer = nn.Linear(input_dim, input_dim)
    
    def forward(self, x):
        if isinstance(x, tuple):
            x = x[0]
        x = self.hide_layer(x)
        return x

linear1 = LinearAdapter(10)
linear2 = LinearAdapter(10)
nor = F.normalize(10)
module = nn.Sequential(linear1, linear2, nor)
module

AttributeError: 'int' object has no attribute 'norm'

In [ ]:
import torch.nn as nn

x = torch.ones(1, 10)
linear = nn.Linear(10, 0)
y = linear(x)
y

/home/huangjialong/miniconda3/envs/biomed/lib/python3.8/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")


tensor([], size=(1, 0), grad_fn=<AddmmBackward0>)

In [ ]:
import open_clip

model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')
tokenizer = open_clip.get_tokenizer('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')

In [ ]:
import os
import torch

fea_dir1 = '/home/huangjialong/projects/BiomedCLIP-PUNCE/extract-features/result-final-gc-features/biomed-test/pt'
fea_dir2 = '/home/huangjialong/projects/BiomedCLIP-PUNCE/extract-features/result-final-gc-features/biomed-test2/pt'
fea_dir3 = '/home/huangjialong/projects/BiomedCLIP-PUNCE/extract-features/result-final-gc-features/biomed2/pt'
pt_file = 'xCY20005897-NILM.pt'

pt_path1 = os.path.join(fea_dir1, pt_file)
pt_path2 = os.path.join(fea_dir2, pt_file)
pt_path3 = os.path.join(fea_dir3, pt_file)
fea1 = torch.load(pt_path1)
fea2 = torch.load(pt_path2)
fea3 = torch.load(pt_path3)
fea2 /= fea3
fea2


tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [ ]:
import torch.nn as nn
import torch
# NLP Example
# NLP Example
# NLP Example
batch, sentence_length, embedding_dim = 20, 5, 10
embedding = torch.randn(batch, sentence_length, embedding_dim)
layer_norm = nn.LayerNorm(embedding_dim)
# Activate module
out = layer_norm(embedding)
out /= embedding
out

tensor([[[-2.0756e+00,  4.8968e-01, -1.1921e+00,  7.8138e-01,  5.2103e-01,
          -1.8302e+00, -1.1896e-01,  3.3987e-01,  2.6367e-01,  5.0438e-01],
         [ 9.6812e-01,  9.8213e-01,  7.0351e-01,  1.1103e+00, -6.4374e-01,
           9.4631e-01, -3.7023e+00,  6.7075e-01,  2.3759e-01,  7.2683e-01],
         [ 2.0717e+00,  8.7473e-01,  1.4393e+00,  1.4921e+00,  5.6588e+00,
           7.5281e-01,  9.3706e-01,  2.1748e+00,  1.4782e+00,  5.8152e-01],
         [ 8.9782e-01,  4.5270e-01,  5.1339e-01,  9.2950e-01,  9.0871e-01,
           6.8978e-01,  5.1612e-01,  7.1402e-01,  2.0777e+01,  9.7726e-01],
         [ 2.0132e+00,  1.1093e+01,  7.7555e-01,  1.2542e-01,  7.6793e-01,
           8.1515e-01, -4.7929e-01,  1.8532e+00,  3.7247e-01,  1.3500e+01]],

        [[ 1.2070e+00,  7.4351e-01,  5.7571e-01,  1.0943e+00,  1.7656e+00,
           6.5129e-01,  7.1894e-01,  1.7322e+00,  8.1733e-01,  7.1680e-01],
         [-1.3851e+00,  1.9621e+00,  1.7829e+00,  1.0089e+00,  1.2072e+00,
           1.8607

In [ ]:
from torchvision import models

pretrained = True
model_baseline = models.resnet50(pretrained=pretrained)
print(model_baseline)

/home/huangjialong/miniconda3/envs/biomed/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/home/huangjialong/miniconda3/envs/biomed/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [ ]:
import open_clip
from torch import nn
class BiomedclipBackbone(nn.Module):
    def __init__(self, without_head: bool = False):
        super(BiomedclipBackbone, self).__init__()
        
        model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')
        if without_head:
            model = model.visual.trunk
        else:
            model = model.visual
        self.model = model
        self.preprocess_val = preprocess_val
    
    def forward(self, x):
        features = self.model(x)
        features /= features.norm(p=2, dim=-1, keepdim=True)
        return features

model = BiomedclipBackbone()

In [ ]:
from torchvision import transforms
preprocess_val = model.preprocess_val
print(preprocess_val)

transfrom = transforms.Compose([
    transforms.Resize((224, 224), interpolation=transforms.InterpolationMode.BICUBIC),
    transforms.CenterCrop((224,224)),
    transforms.ToTensor()])
transfrom

Compose(
    Resize(size=224, interpolation=bicubic, max_size=None, antialias=None)
    CenterCrop(size=(224, 224))
    <function _convert_to_rgb at 0x7f941ee09f70>
    ToTensor()
    Normalize(mean=[0.48145466, 0.4578275, 0.40821073], std=[0.26862954, 0.26130258, 0.27577711])
)


Compose(
    Resize(size=(224, 224), interpolation=bicubic, max_size=None, antialias=None)
    CenterCrop(size=(224, 224))
    ToTensor()
)

In [ ]:
from torchvision import transforms
preprocess_val = model.preprocess_val
print(preprocess_val)
preprocess_list = []
for t in preprocess_val.transforms:
    if isinstance(t, transforms.Normalize):
        continue
    preprocess_list.append(t)
preprocess = transforms.Compose(preprocess_list)
preprocess

CLIPProcessor:
- image_processor: CLIPImageProcessor {
  "_valid_processor_keys": [
    "images",
    "do_resize",
    "size",
    "resample",
    "do_center_crop",
    "crop_size",
    "do_rescale",
    "rescale_factor",
    "do_normalize",
    "image_mean",
    "image_std",
    "do_convert_rgb",
    "return_tensors",
    "data_format",
    "input_data_format"
  ],
  "crop_size": {
    "height": 224,
    "width": 224
  },
  "do_center_crop": true,
  "do_convert_rgb": true,
  "do_normalize": true,
  "do_rescale": true,
  "do_resize": true,
  "image_mean": [
    0.48145466,
    0.4578275,
    0.40821073
  ],
  "image_processor_type": "CLIPImageProcessor",
  "image_std": [
    0.26862954,
    0.26130258,
    0.27577711
  ],
  "resample": 3,
  "rescale_factor": 0.00392156862745098,
  "size": {
    "shortest_edge": 224
  }
}

- tokenizer: CLIPTokenizerFast(name_or_path='vinid/plip', vocab_size=49408, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', trun

AttributeError: 'CLIPProcessor' object has no attribute 'transforms'

In [ ]:
from transformers import CLIPProcessor
import torch
preprocess_val = CLIPProcessor.from_pretrained("vinid/plip")
data = torch.rand(3,224,224)
tmp = preprocess_val(images=data, return_tensors="pt")
tmp['pixel_values']


torch.Size([1, 3, 224, 224])

In [22]:
import torch
from PIL import Image
import open_clip

model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-16', pretrained='laion2b_s34b_b88k')
model.eval()  # model in train mode by default, impacts some models with BatchNorm or stochastic depth active
tokenizer = open_clip.get_tokenizer('ViT-B-16')


In [23]:

image = preprocess(Image.open("3_31.jpg")).unsqueeze(0)
text = tokenizer(["a diagram", "a dog", "a cat"])

with torch.no_grad(), torch.cuda.amp.autocast():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    image_features /= image_features.norm(dim=-1, keepdim=True)
    text_features /= text_features.norm(dim=-1, keepdim=True)

    text_probs = (100.0 * image_features @ text_features.T).softmax(dim=-1)

print("Label probs:", text_probs)  # prints: [[1., 0., 0.]]

Label probs: tensor([[0.8239, 0.1305, 0.0457]])


In [4]:
image.shape

torch.Size([1, 3, 224, 224])

In [1]:
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("vinid/plip")
processor = CLIPProcessor.from_pretrained("vinid/plip")

image = Image.open("3_31.jpg")

inputs = processor(text=["a photo of label 1", "a photo of label 2"],
                    images=image, return_tensors="pt", padding=True)


Unused or unrecognized kwargs: padding.


In [1]:
import timm
from PIL import Image
from torchvision import transforms
import torch

tile_encoder = timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True)

transform = transforms.Compose(
    [
        transforms.Resize(256, interpolation=transforms.InterpolationMode.BICUBIC),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ]
)


GatedRepoError: 401 Client Error. (Request ID: Root=1-66a0b5c8-66547f145532fb2608aa9af8;2194cac4-4391-4caa-9273-0c71ba705963)

Cannot access gated repo for url https://hf-mirror.com/prov-gigapath/prov-gigapath/resolve/main/model.safetensors.
Access to model prov-gigapath/prov-gigapath is restricted. You must be authenticated to access it.

In [1]:
import torch
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(3, 5)
tensor_cat = torch.cat((tensor1, tensor2), dim=-1)
tensor_cat.shape

torch.Size([3, 9])

In [44]:
# 重新定义混淆矩阵和类别数量
cm_manual = [
    [2, 1, 0],  # 实际类别 0
    [0, 1, 2],  # 实际类别 1
    [1, 2, 0]   # 实际类别 2
]
num_classes = len(cm_manual)  # 类别数量

# 重新计算行和列的总计
row_totals = [sum(row) for row in cm_manual]
col_totals = [sum(col) for col in zip(*cm_manual)]
total = sum(row_totals)
class_labels = ['NILM', 'ASC-US', 'ASC-H']

# 重新格式化混淆矩阵，确保第一行包含类别名称
formatted_cm_with_labels = "实际\预测\t|\t" + "\t|\t".join(map(str, class_labels)) + "\t|\t总计\n"
formatted_cm_with_labels += "-" * ((len(class_labels)+2) * 16) + "\n"
for i, label in enumerate(class_labels):
    formatted_cm_with_labels += label + "\t\t|\t"
    for j in range(num_classes):
        formatted_cm_with_labels += str(cm_manual[i][j]) + "\t|\t"
    formatted_cm_with_labels += str(row_totals[i]) + "\n"
    formatted_cm_with_labels += "-" * ((len(class_labels)+2) * 16) + "\n"
formatted_cm_with_labels += "总计\t\t|\t" + "\t|\t".join(map(str, col_totals)) + "\t|\t" + str(total) + "\n"

print(formatted_cm_with_labels)


实际\预测	|	NILM	|	ASC-US	|	ASC-H	|	总计
--------------------------------------------------------------------------------
NILM		|	2	|	1	|	0	|	3
--------------------------------------------------------------------------------
ASC-US		|	0	|	1	|	2	|	3
--------------------------------------------------------------------------------
ASC-H		|	1	|	2	|	0	|	3
--------------------------------------------------------------------------------
总计		|	3	|	4	|	2	|	9



In [1]:
import torch

def find_first_less_than(tensor, target):
    # 找到所有小于目标值的元素的位置
    less_than_target = torch.where(tensor < target)
    
    # 如果没有找到，返回-1
    if len(less_than_target[0]) == 0:
        return -1
    
    # 返回第一个小于目标值的元素的位置
    return (less_than_target[0][0], less_than_target[1][0])

# 示例张量
tensor = torch.tensor([[10, 20, 30, 40],
                       [50, 60, 70, 80],
                       [90, 100, 110, 120]])

# 目标值
target_value = 75

# 调用函数
position = find_first_less_than(tensor, target_value)

print(f"第一个小于{target_value}的元素的位置是: {position}")


第一个小于75的元素的位置是: (tensor(0), tensor(0))
